services:
  db:
    image: postgres:18.3-alpine
    container_name: postgres-love4animals
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: love4animals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

pgadmin:
  imaage: dpage/pgadmin4:9.14.0
  container_name: pgadmin-ui
  restart: always
  environment:
    - PGADMIN_DEFAULT_EMAIL: test@test.com
    - PGADMIN_DEFAULT_PASSWORD: test
  ports:
  - "5050:80"
  depends_on:
  - db

volumes:
  postgres_data: